### ISSUE TITLE
Rebuild image

### ISSUE THREAD

**Issue by lociii** [gmelillo/docker-dehydrated-lexicon#1]
Hey Gabriel,

thanks for your work on this image. Yesterday I've added a new provider to lexicon which got merged in and released today.

Could you please rebuild the image on Docker Hub to include the latest lexicon releas?

Thanks!

**Comment by lociii** [comment]
Added a pull request with fixes so that the release will also be up to date in #2

**Comment by gmelillo** [comment]
Merged, thanks for the contribution :)
